<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/*
 * Modified to include the "product:price:valueAddedTaxIncluded" property
 * and to include VAT in the product:price:amount property.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<meta property="og:type" content="og:product" />
<meta property="og:title" content="<?php echo $block->escapeHtml($block->getProduct()->getName()); ?>" />
<meta property="og:image" content="<?php echo $block->escapeUrl($block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()); ?>" />
<meta property="og:description" content="<?php echo $block->escapeHtml($block->getProduct()->getShortDescription()); ?>" />
<meta property="og:url" content="<?php echo $block->escapeUrl($block->getProduct()->getProductUrl()); ?>" />
<?php if ($priceAmount = $block->getProduct()->getFinalPrice()):?>
    <?php $priceAmountIncVat = $priceAmount * 1.2; ?>
    <meta property="product:price:amount" content="<?php /* @escapeNotVerified */ echo $priceAmountIncVat; ?>"/>
    <?php echo $block->getChildHtml('meta.currency'); ?>
    <meta property="product:price:valueAddedTaxIncluded" content="True"/>
<?php endif;?>
