<?php
/**
 * Copyright © 2017 OPENXTRA Ltd.. All rights reserved.
 * See COPYING.txt for license details.
 */

// Read the copyright statement entered in the admin configuration system
$copyrightText = $block->getCopyright();
?>
<small class="copyright">
    <div class="page-main">
        <span class="fb-before">
            <p>Company Registration No. 4641663. VAT No. GB808975581. WEEE Registration No. WEE/EK0053TQ</p>
	</span>
        <span><?php echo $copyrightText; ?></span>
        <span class="fb-after"></span>
    </div>
</small>
