<?php
/**
 * Copyright (c) 2016 OPENXTRA Limited. All rights reserved.
 * See copying.txt for licence info.
 */

$imagePath = $block->getViewFileUrl('images/s_telephone.gif');
?>
<div class="phone-solicitation">
<img src="<?php echo $imagePath ?>" alt="Call OPENXTRA" width="17" height="14" />
<span class="action-text" style="font-size: 140%; vertical-align: top ">
<strong class="vertical-align: top">FREEPHONE <a href="tel:08006121357">0800 612 1357</a></strong>
</span>
</div>
